'use strict';

const { isPostgres } = require('../dialect-helper');

/**
 * DATABASE_SCHEMA.md §6.2 + §9.1.
 *
 * customer_ledger_entries is deliberately NOT a Strapi content type: §9.1
 * lists it under "Managed as custom table (service-only)" specifically so
 * that no admin-panel action can ever mutate financial history. It is
 * created here via a raw migration and is read/written exclusively through
 * src/api/customer/services/ledger.ts using `strapi.db.connection` (Knex).
 *
 * `created_by_id` / `approved_by_id` are plain BIGINT columns (no FK) because
 * `app_users` is out of Milestone 1 scope — the DDL in the spec references
 * app_users(id), which does not exist yet.
 *
 * Because this table lives outside the Content API, Strapi does not
 * auto-generate `document_id` for it the way it does for content types
 * (see the "Conventions" note at the top of DATABASE_SCHEMA.md) — it is
 * generated by ledger.service.ts on insert instead.
 *
 * SQLite branch: dev-only local-testing path (no Postgres credentials
 * available). Same columns/checks with SQLite-compatible types; the
 * append-only guarantee is reproduced with SQLite triggers (RAISE(ABORT))
 * instead of a plpgsql function+trigger pair.
 */
module.exports = {
  async up(trx) {
    if (isPostgres(trx)) {
      await trx.raw(`
        CREATE TABLE customer_ledger_entries (
          id                    BIGSERIAL PRIMARY KEY,
          document_id           VARCHAR(255) UNIQUE NOT NULL,
          store_id              BIGINT NOT NULL REFERENCES stores(id),
          customer_id           BIGINT NOT NULL REFERENCES customers(id),
          entry_type            TEXT NOT NULL CHECK (entry_type IN
              ('OPENING_BALANCE','SALE_CREDIT','PAYMENT_RECEIVED','CREDIT_NOTE','DEBIT_NOTE','WRITE_OFF','ADJUSTMENT')),
          direction             TEXT NOT NULL CHECK (direction IN ('DEBIT','CREDIT')),
          amount_paise          BIGINT NOT NULL CHECK (amount_paise > 0),
          running_balance_paise BIGINT NOT NULL,
          reference_type        TEXT CHECK (reference_type IN ('ORDER','CUSTOMER_PAYMENT','ADJUSTMENT','SYSTEM')),
          reference_id          BIGINT,
          entry_date            DATE NOT NULL,
          note                  TEXT,
          created_by_id         BIGINT,
          approved_by_id        BIGINT,
          created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
        )
      `);

      await trx.raw(`CREATE INDEX idx_cle_customer ON customer_ledger_entries(customer_id, id DESC)`);
      await trx.raw(`CREATE INDEX idx_cle_store_date ON customer_ledger_entries(store_id, entry_date)`);
      await trx.raw(`CREATE INDEX idx_cle_ref ON customer_ledger_entries(reference_type, reference_id)`);

      // Rule LED-3: no row is ever updated or deleted.
      await trx.raw(`
        CREATE OR REPLACE FUNCTION forbid_customer_ledger_mutation()
        RETURNS TRIGGER AS $$
        BEGIN
          RAISE EXCEPTION 'customer_ledger_entries is append-only: % is not permitted (id=%)', TG_OP, OLD.id;
        END;
        $$ LANGUAGE plpgsql;
      `);
      await trx.raw(`
        CREATE TRIGGER trg_customer_ledger_append_only
        BEFORE UPDATE OR DELETE ON customer_ledger_entries
        FOR EACH ROW EXECUTE FUNCTION forbid_customer_ledger_mutation();
      `);
      return;
    }

    await trx.raw(`
      CREATE TABLE customer_ledger_entries (
        id                    INTEGER PRIMARY KEY AUTOINCREMENT,
        document_id           TEXT UNIQUE NOT NULL,
        store_id              INTEGER NOT NULL REFERENCES stores(id),
        customer_id           INTEGER NOT NULL REFERENCES customers(id),
        entry_type            TEXT NOT NULL CHECK (entry_type IN
            ('OPENING_BALANCE','SALE_CREDIT','PAYMENT_RECEIVED','CREDIT_NOTE','DEBIT_NOTE','WRITE_OFF','ADJUSTMENT')),
        direction             TEXT NOT NULL CHECK (direction IN ('DEBIT','CREDIT')),
        amount_paise          INTEGER NOT NULL CHECK (amount_paise > 0),
        running_balance_paise INTEGER NOT NULL,
        reference_type        TEXT CHECK (reference_type IN ('ORDER','CUSTOMER_PAYMENT','ADJUSTMENT','SYSTEM')),
        reference_id          INTEGER,
        entry_date            TEXT NOT NULL,
        note                  TEXT,
        created_by_id         INTEGER,
        approved_by_id        INTEGER,
        created_at            TEXT NOT NULL DEFAULT (datetime('now'))
      )
    `);
    await trx.raw(`CREATE INDEX idx_cle_customer ON customer_ledger_entries(customer_id, id DESC)`);
    await trx.raw(`CREATE INDEX idx_cle_store_date ON customer_ledger_entries(store_id, entry_date)`);
    await trx.raw(`CREATE INDEX idx_cle_ref ON customer_ledger_entries(reference_type, reference_id)`);
    await trx.raw(`
      CREATE TRIGGER trg_cle_no_update BEFORE UPDATE ON customer_ledger_entries
      BEGIN SELECT RAISE(ABORT, 'customer_ledger_entries is append-only'); END
    `);
    await trx.raw(`
      CREATE TRIGGER trg_cle_no_delete BEFORE DELETE ON customer_ledger_entries
      BEGIN SELECT RAISE(ABORT, 'customer_ledger_entries is append-only'); END
    `);
  },
  async down(trx) {
    if (!isPostgres(trx)) {
      await trx.raw('DROP TABLE IF EXISTS customer_ledger_entries');
      return;
    }
    await trx.raw('DROP TRIGGER IF EXISTS trg_customer_ledger_append_only ON customer_ledger_entries');
    await trx.raw('DROP FUNCTION IF EXISTS forbid_customer_ledger_mutation()');
    await trx.raw('DROP TABLE IF EXISTS customer_ledger_entries');
  },
};
